### ISSUE TITLE
multi-dimensional array initialization

### ISSUE THREAD

**Issue by AmuletDeters** [compuphase/pawn#12]
I am having an issue on 4.0.4733 with properly initializing multi-dimensional arrays. The following example will demonstrate the problem.

    main()
    {
    	new dropDownStrings[][]{} = [ ["Never","Niemals"] , ["Warning_Only","Nur Warnung"] ,["Reject_Only","Nur_Toleranz"] , ["Warning_or_Reject","Warnung_oder_Toleranz"] ] ;
    	for(new a = 0; a < 4; a++)
    		for(new b = 0; b < 2; b++)
    		{
    			print  dropDownStrings[a][b];
    			print "\n";
    		}
    }

I would expect the output:
    `Never`
    `Niemals`
    `Warning_Only`
    `Nur Warnung`
    `Reject_Only`
    `Nur_Toleranz`
    `Warning_or_Reject`
    `Warnung_oder_Toleranz`

but instead I get this:
    `Never`
    `Niemals`
    `Warning_Only`
    `Only`
    `Nur Warnung`
    `ung`
    `Nur_Toleranz`

It looks like the compiler sees the first entry is (in my case) 2 cells long and makes some assumptions about the rest of the initializer. Making the first string very long fixes this. Another quick workaround was to explicitly state a length of the last dimension of the array:
    `dropDownStrings[][]{25}`

Is this a bug or am I dong something wrong?

**Comment by compuphase** [comment]
This is now fixed.
