### ISSUE TITLE
labels with the same name

### ISSUE THREAD

**Issue by Daniel-Cortez** [compuphase/pawn#21]
Originally discovered at pro-pawn.ru by a forum member nicknamed Blood:
	http://pro-pawn.ru/showthread.php?14157

The compiler allows to make labels with the same name within a function scope.
If one defines two or more labels with identical names and use `goto` to one of those labels, the compiler will make a jump at the last label with that name.
Sometimes this can lead to unexpected (or unintuitive) results.

Example:
```Pawn
#include <console>

main()
{
	goto test_label;
test_label:
	print("test_label 1\n");
	return;
test_label:
	print("test_label 2\n");
}
```
One might expect it to print "test_label 1", but it actually outputs "test_label 2".
The compiler warns about unreachable code (even though `goto test_label` leads right to that code), but it doesn't even tell anything about the second `test_label` shadowing the first one.
Normally I'd ask if this is a bug or it's intended to be so, but since [Pawn is designed to be a robust language](http://www.compuphase.com/pawn/pawnfeatures.htm#ROBUST), I guess this should be considered a bug. The compiler should either disallow using the same name for labels more than once per function or at least give a warning message.

**Comment by compuphase** [comment]
The compiler should not allow a double definition of the same label.

**Comment by compuphase** [comment]
Fixed in commit  https://github.com/compuphase/pawn/commit/09070ba7da3c032892287f6a7068ec60e0d39f02.
