### ISSUE TITLE
OOB access in `findfunction`

### ISSUE THREAD

**Issue by Y-Less** [compuphase/pawn#36]
```c
for (i=0; list[i].name!=NULL && (i<number || number==-1); i++)
```

Checks `list[i].name` before checking `i < number`, which is OOB when using an exact count and no sentinel entry.  See:

https://github.com/Zeex/sampgdk/issues/188

Edit: Not an overflow, since nothing is written, but still OOB.

**Comment by compuphase** [comment]
I confirmed this to be a bug. It is now fixed.
Thanks.
