### ISSUE TITLE
Documentation source

### ISSUE THREAD

**Issue by Y-Less** [compuphase/pawn#44]
The repo only has the pdf versions of `Pawn_Language_Guide` etc.  It would be nice to be able to update those as well.

**Comment by sskras** [comment]
One idea would be to use some lightweight markup language.  Eg. AsciiDoc:
https://www.writethedocs.org/guide/writing/asciidoc/#why-use-asciidoc

GitHub renders it mostly fine (only breaking at eg. nested lists with depth > 5 or so).

All `.pdf` files then could be generated using eg. **Asciidoctor PDF**:
https://github.com/asciidoctor/asciidoctor-pdf#overview

**Comment by compuphase** [comment]
Documentation is written in plain TeX, using a macro package and additional utilities that have been developed in-house for past 30 years. You would only be able to use those sources, if you set up TeX in exactly the way we do. In practice, for anyone not working at our office, it is easier to copy & paste the text into a word processor of choice, and reformat.

As for the question why we use a home-grown setup of a old text processor with a primitive macro set... that is a long story.
