### ISSUE TITLE
Compilation of fib.p example cause infinite loop

### ISSUE THREAD

**Issue by l3VGV** [compuphase/pawn#58]
Version of compiler is 4.0.5749.

OS Windows 10, compiler is MS Visual C++ 2019.

Code will be looping infinitely, slowly growing in memory, 
`while (!matchtoken('}')){     /* repeat until compound statement is closed */` 
file sc1, line 5900

Couse is, file fib1.p is UTF8 with UNIX LF line termination, after changing it to CR LF - compiled just fine.
Another fix is to add semicolon at the and of the string 
`    print "Enter a value: "`
in fib.p

I wasnt able to identify what kind of fix can be applied to pawn complier itself.

**Comment by compuphase** [comment]
Commit e204c9468c1f7b509610868345c5fc4293842768 fixes a problem with parsing UTF8 with a BOM (byte-order-mark).
However, I did not experience an infinite loop (instead I got an error message).
