### ISSUE TITLE
Colors in IDE

### ISSUE THREAD

**Issue by namazso** [compuphase/pawn#62]
Are they broken or did i just fail to understand what they change?

![image](https://user-images.githubusercontent.com/8676443/126872503-1774b9a4-e522-4f22-92e2-f79b12c42ea2.png)

**Comment by compuphase** [comment]
It is broken, at least for the background colour and the "standard text" colour. I will look into it.

**Comment by compuphase** [comment]
Fixed in commit e58b610a4b64b177c140916674f4d32b0ea6de2c in the [Quincy project](https://github.com/compuphase/Quincy).
