### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by namazso** [compuphase/pawn#63]
![image](https://user-images.githubusercontent.com/8676443/126889130-278817f1-1f1e-416b-8121-f1c7ad7ca180.png)
here where the documentation says `STK = STK + [STK]` which would add the return address to STK
![image](https://user-images.githubusercontent.com/8676443/126890371-ffaa519b-c16b-4323-8188-fe62630859b2.png)
here, the range is actually filled with `PRI`, rather than `[PRI]`

**Comment by compuphase** [comment]
Fixed in commit 9b7fc0856da0b965dee7c73310ccdf952dcce417. Thank you for the report.
