### ISSUE TITLE
Problem debugging in wxquincy

### ISSUE THREAD

**Issue by RallyTronics** [compuphase/pawn#79]
I am working in Win 10.  When I try to debug some of the example scripts ( i.e. sieve.p ) using `F5` in quincy I get a popup error:

`Couldn't retrieve information about list control item 0.`

If I click the run button `CTRL+F5` scripts run as expected.

I am building with Debug info set to `Symbolic debugging` and instruction set at `Full`

Is there a setting/option I am missing to make this work?

**Comment by steve64** [comment]
I faced the same issue with latest release. Any answer to this bug since almost 2 years?

**Comment by compuphase** [comment]
See issue  #91.
