### ISSUE TITLE
Segmentation fault in pawncc

### ISSUE THREAD

**Issue by sfzhi** [compuphase/pawn#92]
Using a freshly-built pawn-4.1.7152 on Linux x86_64:
```
$ pawncc foo -o foo
Pawn compiler 4.1.7152                  Copyright (c) 1997-2024, CompuPhase

Segmentation fault
```
The cause is very simple: the [call to mkstemp(...)](https://github.com/compuphase/pawn/blob/main/compiler/sc1.c#L560) is invalid. The function requires a **writable** character buffer.

**Comment by compuphase** [comment]
Corrected in commit 69b90f2626c179dc1649dcc111008f6199916410.
Thank you for reporting it.
